[package]
name = "oram_simulation"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
tfhe = { version = "0.7.2", features = [ "boolean", "shortint", "integer", "x86_64-unix" ] }
rand = "0.8.4"